apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webpage
  labels:
    app: simple-webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webpage
  template:
    metadata:
      labels:
        app: simple-webpage
    spec:
      containers:
        - name: simple-webpage
          image: aididalam/simple-webpage:main-7
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
